# Generated by Django 4.0.4 on 2022-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MostRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('runs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MostWickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('wickets', models.CharField(max_length=100)),
            ],
        ),
    ]
