# Generated by Django 4.0.4 on 2022-04-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sponsors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Sponsor',
        ),
    ]
