# Generated by Django 4.0.4 on 2022-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_writeup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPerformersBatsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('matches', models.CharField(max_length=100)),
                ('innings', models.CharField(max_length=100)),
                ('runs', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Top Performers Batsmen',
            },
        ),
        migrations.CreateModel(
            name='TopPerformersBowler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('matches', models.CharField(max_length=100)),
                ('overs', models.CharField(max_length=100)),
                ('runs', models.CharField(max_length=100)),
                ('wickets', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Top Performers Bowlers',
            },
        ),
    ]
