# Generated by Django 4.0.4 on 2022-04-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_topperformersbatsman_topperformersbowler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topperformersbatsman',
            name='team',
        ),
        migrations.RemoveField(
            model_name='topperformersbowler',
            name='team',
        ),
    ]
