# Generated by Django 4.0.4 on 2022-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_topperformersbowler_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topperformersbatsman',
            name='innings',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topperformersbatsman',
            name='matches',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topperformersbatsman',
            name='runs',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topperformersbowler',
            name='matches',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topperformersbowler',
            name='overs',
            field=models.FloatField(),
        ),
    ]
