# Generated by Django 4.0.4 on 2022-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_topperformersbatsman_innings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topperformersbowler',
            name='matches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topperformersbowler',
            name='runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topperformersbowler',
            name='wickets',
            field=models.IntegerField(),
        ),
    ]
