# Generated by Django 4.0.4 on 2022-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_topperformersbowler_matches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topperformersbatsman',
            name='innings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topperformersbatsman',
            name='matches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topperformersbatsman',
            name='runs',
            field=models.IntegerField(),
        ),
    ]
