# Generated by Django 4.0.4 on 2022-05-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_topperformersbatsman_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topperformersbowler',
            name='maidens',
            field=models.IntegerField(default=0),
        ),
    ]
