# Generated by Django 4.0.4 on 2022-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_topperformersbowler_maidens'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiBatStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('innings', models.IntegerField()),
                ('not_out', models.IntegerField(default=0)),
                ('runs', models.IntegerField()),
                ('average', models.FloatField(default=0)),
                ('top_score', models.CharField(max_length=100)),
                ('fifty', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('dots', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Semi-Final Batting Stats',
                'ordering': ('-runs',),
            },
        ),
        migrations.CreateModel(
            name='SemiBowlStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('overs', models.IntegerField()),
                ('maidens', models.IntegerField(default=0)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('wides', models.IntegerField(default=0)),
                ('no_balls', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0)),
                ('econ', models.FloatField(default=0)),
                ('best', models.CharField(max_length=100)),
                ('top_score', models.CharField(max_length=100)),
                ('five_wickets', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('dots', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Semi-Final Bowling Stats',
                'ordering': ('-wickets',),
            },
        ),
        migrations.AlterModelOptions(
            name='topperformersbowler',
            options={'ordering': ('-wickets', 'runs'), 'verbose_name_plural': 'Top Performers Bowlers'},
        ),
    ]
