# Generated by Django 4.0.4 on 2022-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_semibatstats_semibowlstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semibatstats',
            name='innings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='semibatstats',
            name='matches',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='semibatstats',
            name='not_out',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='semibowlstats',
            name='matches',
            field=models.IntegerField(default=1),
        ),
    ]
