# Generated by Django 4.0.4 on 2022-05-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_semibatstats_innings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semibatstats',
            name='average',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
