# Generated by Django 4.0.4 on 2022-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_semibatstats_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semibatstats',
            name='runs',
            field=models.CharField(max_length=100),
        ),
    ]
