# Generated by Django 4.0.4 on 2022-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_semibatstats_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semibowlstats',
            name='overs',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='semibowlstats',
            name='wickets',
            field=models.IntegerField(default=1),
        ),
    ]
