# Generated by Django 4.0.4 on 2022-05-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_semibowlstats_overs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semibowlstats',
            name='five_wickets',
        ),
        migrations.RemoveField(
            model_name='semibowlstats',
            name='top_score',
        ),
    ]
