# Generated by Django 4.0.4 on 2022-05-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_semibowlstats_five_wickets_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeup',
            options={'ordering': ['-id']},
        ),
    ]
