# Generated by Django 4.0.4 on 2022-05-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_writeup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationCeremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winners', models.CharField(max_length=100)),
                ('second', models.CharField(max_length=100)),
                ('most_runs', models.CharField(max_length=100)),
                ('most_wickets', models.CharField(max_length=100)),
                ('most_catches', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
    ]
